version: '3.8'

services:
  user_service_api:
    container_name: user_service
    image: userservice:latest
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver    
  product_service_api:
    container_name: product_service
    image: productservice:latest
    ports:
      - "8081:8080"
    depends_on:
      - sqlserver  
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password1*
    ports:
      - "1433:1433" 
