version: '3.8'

services:
  productservice:
    image: productsservice:latest
    build:
      context: .
      dockerfile: ProductService/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=InnoShopDB;User Id=sa;Password=MySecurePassword123!;
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      - SA_PASSWORD=MySecurePassword123!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - dbdata:/var/opt/mssql

volumes:
  dbdata:
